Repository thingsboard/tbmq, pull requests merged in 2024-11, with the labels that each got.

#176 Fix WS client admin settings with missing parameter
  application/src/main/java/org/thingsboard/mqtt/broker/install/ThingsboardMqttBrokerInstallService.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/install/data/WebSocketClientSettings.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/install/update/DefaultDataUpdateService.java
Labels: Bug

#178 Refactor DevicePublishMsg processing to eliminate unnecessary transformation to PublishMsg
  application/src/main/java/org/thingsboard/mqtt/broker/actors/device/PersistedDeviceActorMessageProcessor.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/DefaultMqttMessageCreator.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/DefaultPublishMsgDeliveryService.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/MqttMessageGenerator.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/PublishMsgDeliveryService.java
  application/src/main/java/org/thingsboard/mqtt/broker/session/TopicAliasCtx.java
  application/src/test/java/org/thingsboard/mqtt/broker/actors/device/PersistedDeviceActorMessageProcessorTest.java
  application/src/test/java/org/thingsboard/mqtt/broker/session/TopicAliasCtxTest.java
Labels: Ignore for release

#182 Bug/last will delivery
  application/src/main/java/org/thingsboard/mqtt/broker/actors/client/ClientActor.java
  application/src/main/java/org/thingsboard/mqtt/broker/actors/config/ActorsConfiguration.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/will/DefaultLastWillService.java
  application/src/main/java/org/thingsboard/mqtt/broker/util/MqttPropertiesUtil.java
  application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/will/DefaultLastWillServiceTest.java
  common/actor/src/main/java/org/thingsboard/mqtt/broker/actors/DefaultTbActorSystem.java
  common/actor/src/main/java/org/thingsboard/mqtt/broker/actors/TbActorSystem.java
Labels: Bug

#183 Lettuce updates
  application/src/main/resources/thingsboard-mqtt-broker.yml
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/ClusterAwareLettuceConnectionManager.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/DefaultLettuceConnectionManager.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/LettuceConfig.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/LettuceConnectionManager.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/LettuceTopologyRefreshConfig.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/TBRedisCacheConfiguration.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/TBRedisClusterConfiguration.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/TBRedisSentinelConfiguration.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/TBRedisStandaloneConfiguration.java
  common/cache/src/test/java/org/thingsboard/mqtt/broker/cache/TbRedisCacheConfigurationTest.java
  dao/src/main/java/org/thingsboard/mqtt/broker/dao/messages/ClientIdLastPacketIdCacheKey.java
  dao/src/main/java/org/thingsboard/mqtt/broker/dao/messages/ClientIdMessagesCacheKey.java
  dao/src/main/java/org/thingsboard/mqtt/broker/dao/messages/DeviceMsgServiceImpl.java
  dao/src/test/resources/application-test.properties
  docker/cache-redis-cluster.env
  docker/cache-redis-sentinel.env
  k8s/aws/tb-broker-cache-configmap.yml
  k8s/azure/tb-broker-cache-configmap.yml
Labels: Core, Ignore for release

#185 Allow ; as a character in kafka configs
  application/src/main/java/org/thingsboard/mqtt/broker/config/AbstractMsgsRateLimitsConfiguration.java
  application/src/main/java/org/thingsboard/mqtt/broker/config/SwaggerConfiguration.java
  application/src/main/java/org/thingsboard/mqtt/broker/controller/TimeseriesController.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/install/SqlDatabaseUpgradeService.java
  application/src/main/java/org/thingsboard/mqtt/broker/ssl/config/AbstractSslCredentials.java
  application/src/main/java/org/thingsboard/mqtt/broker/util/MiscUtils.java
  application/src/test/java/org/thingsboard/mqtt/broker/AbstractPubSubIntegrationTest.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/CacheConstants.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/JedisClusterNodesUtil.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/TBRedisCacheConfiguration.java
  common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/BrokerConstants.java
  common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/util/StringUtils.java
  common/queue/pom.xml
  common/queue/src/main/java/org/thingsboard/mqtt/broker/queue/TbQueueAdmin.java
  common/queue/src/main/java/org/thingsboard/mqtt/broker/queue/kafka/TbKafkaAdmin.java
  common/queue/src/main/java/org/thingsboard/mqtt/broker/queue/kafka/TbKafkaConsumerTemplate.java
  common/queue/src/main/java/org/thingsboard/mqtt/broker/queue/kafka/settings/StatsConsumerKafkaSettings.java
  common/queue/src/main/java/org/thingsboard/mqtt/broker/queue/kafka/settings/TbKafkaAdminSettings.java
  common/queue/src/main/java/org/thingsboard/mqtt/broker/queue/kafka/settings/TbKafkaConsumerSettings.java
  common/queue/src/main/java/org/thingsboard/mqtt/broker/queue/kafka/settings/TbKafkaProducerSettings.java
  common/queue/src/main/java/org/thingsboard/mqtt/broker/queue/kafka/stats/TbKafkaConsumerStatisticConfig.java
  common/queue/src/main/java/org/thingsboard/mqtt/broker/queue/kafka/stats/TbKafkaConsumerStatsService.java
  common/queue/src/main/java/org/thingsboard/mqtt/broker/queue/util/QueueUtil.java
  common/queue/src/test/java/org/thingsboard/mqtt/broker/queue/util/QueueUtilTest.java
  common/queue/src/test/resources/config.txt
  common/queue/src/test/resources/logback.xml
  common/stats/src/main/java/org/thingsboard/mqtt/broker/common/stats/DefaultStatsFactory.java
Labels: Enhancement, Core
