Repository thingsboard/tbmq, pull requests merged in 2024-08, with the labels that each got.

#144 Feature/traffic metric
  application/src/main/java/org/thingsboard/mqtt/broker/config/SecurityConfiguration.java
  application/src/main/java/org/thingsboard/mqtt/broker/server/AbstractMqttChannelInitializer.java
  application/src/main/java/org/thingsboard/mqtt/broker/server/MqttHandlerCtx.java
  application/src/main/java/org/thingsboard/mqtt/broker/server/MqttHandlerFactory.java
  application/src/main/java/org/thingsboard/mqtt/broker/server/MqttHandlerFactoryImpl.java
  application/src/main/java/org/thingsboard/mqtt/broker/server/MqttSessionHandler.java
  application/src/main/java/org/thingsboard/mqtt/broker/server/traffic/DuplexTrafficHandler.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/historical/stats/HistoricalStatsTotalConsumer.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/historical/stats/TbMessageStatsReportClient.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/historical/stats/TbMessageStatsReportClientImpl.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/security/auth/jwt/RefreshTokenProcessingFilter.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/security/auth/rest/RestLoginProcessingFilter.java
  application/src/main/java/org/thingsboard/mqtt/broker/util/BytesUtil.java
  common/util/src/main/java/org/thingsboard/mqtt/broker/common/util/BrokerConstants.java
  common/util/src/main/java/org/thingsboard/mqtt/broker/common/util/JacksonUtil.java
Labels: Enhancement

#143 Improvements to the upgrade script logic
  application/src/main/data/upgrade/1.2.1/schema_update.sql
  application/src/main/java/org/thingsboard/mqtt/broker/service/install/SqlDatabaseUpgradeService.java
Labels: Core

#146 Added stats chart key processedBytes
  ui-ngx/src/app/core/http/stats.service.ts
  ui-ngx/src/app/core/utils.ts
  ui-ngx/src/app/modules/home/components/wizard/connection-wizard-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/monitoring/monitoring.component.html
  ui-ngx/src/app/modules/home/pages/monitoring/monitoring.component.ts
  ui-ngx/src/app/shared/models/chart.model.ts
  ui-ngx/src/app/shared/models/ws-client.model.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Enhancement, UI

#148 ws-client: on topic subscription added subscriptionIdentifier
  ui-ngx/src/app/core/http/mqtt-js-client.service.ts
Labels: Ignore for release
