Repository thingsboard/tbmq, pull requests merged in 2024-10, with the labels that each got.

#165 Updated default params and added write-and-flush option for persisted device clients
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/DefaultPublishMsgDeliveryService.java
  application/src/main/resources/thingsboard-mqtt-broker.yml
Labels: Enhancement, Core

#166 Improved client sessions filter
  application/src/main/java/org/thingsboard/mqtt/broker/controller/ClientSessionController.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/client/session/ClientSessionPageInfosImpl.java
  application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/client/session/ClientSessionPageInfosImplTest.java
  common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/ClientSessionQuery.java
  common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/client/session/SubscriptionOperation.java
  ui-ngx/src/app/modules/home/pages/sessions/session-filter-config.component.html
  ui-ngx/src/app/modules/home/pages/sessions/session-filter-config.component.ts
  ui-ngx/src/app/modules/home/pages/sessions/sessions-table-config.ts
  ui-ngx/src/app/shared/models/query/query.models.ts
  ui-ngx/src/app/shared/models/session.model.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Core

#167 Improved MQTT client credentials filter
  application/src/main/java/org/thingsboard/mqtt/broker/controller/MqttClientCredentialsController.java
  common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/client/credentials/ClientCredentialsQuery.java
  dao/src/main/java/org/thingsboard/mqtt/broker/dao/client/DefaultMqttClientCredentialsDao.java
  dao/src/main/java/org/thingsboard/mqtt/broker/dao/client/MqttClientCredentialsRepository.java
  dao/src/test/java/org/thingsboard/mqtt/broker/dao/service/MqttClientCredentialsServiceTest.java
  ui-ngx/src/app/modules/home/pages/client-credentials/client-credentials-filter-config.component.html
  ui-ngx/src/app/modules/home/pages/client-credentials/client-credentials-filter-config.component.ts
  ui-ngx/src/app/modules/home/pages/client-credentials/client-credentials-table-config.resolver.ts
  ui-ngx/src/app/shared/models/credentials.model.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Core

#169 TBMQ latest version available moved to backend
  application/src/main/java/org/thingsboard/mqtt/broker/controller/SystemInfoController.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/http/TBMQReleaseService.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/retain/RetainedMsgListenerServiceImpl.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/provider/AbstractServiceProvider.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/ttl/TimeseriesCleanUpService.java
  common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/BrokerConstants.java
  common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/util/BytesUtil.java
  ui-ngx/src/app/core/http/config.service.ts
  ui-ngx/src/app/modules/home/components/version-card/version-card.component.ts
  ui-ngx/src/app/shared/models/config.model.ts
Labels: Core

#170 Vulnerabilities fix
  msa/black-box-tests/pom.xml
  pom.xml
Labels: Core

#172 Allow edit system WS client credentials
  dao/src/main/java/org/thingsboard/mqtt/broker/dao/client/MqttClientCredentialsServiceImpl.java
Labels: Bug

#174 Migration of Device publish messages handling from Jedis to Lettuce
  application/src/main/data/upgrade/1.4.0/schema_update.sql
  application/src/main/java/org/thingsboard/mqtt/broker/actors/device/PersistedDeviceActorMessageProcessor.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/install/SqlDatabaseUpgradeService.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/device/DevicePersistenceProcessorImpl.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/device/processing/DeviceMsgProcessor.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/device/processing/DeviceMsgProcessorImpl.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/device/processing/DevicePackProcessingContext.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/device/processing/DevicePackProcessingResult.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/device/processing/DevicePublishMsgListAndPrevPacketId.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/device/queue/DeviceMsgQueueConsumerImpl.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/stats/DefaultDeviceProcessorStats.java
  application/src/main/resources/thingsboard-mqtt-broker.yml
  application/src/test/java/org/thingsboard/mqtt/broker/actors/device/PersistedDeviceActorMessageProcessorTest.java
  application/src/test/java/org/thingsboard/mqtt/broker/cache/RedisCacheDefaultConfigurationTest.java
  application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/device/DevicePersistenceProcessorImplTest.java
  application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/device/processing/DeviceMsgProcessorImplTest.java
  application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/device/processing/DevicePackProcessingContextTest.java
  common/cache/pom.xml
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/AbstractLettuceConnectionManager.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/ClusterAwareLettuceConnectionManager.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/DefaultLettuceConnectionManager.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/LettuceConnectionManager.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/TBRedisCacheConfiguration.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/TBRedisClusterConfiguration.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/TBRedisSentinelConfiguration.java
  common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/TBRedisStandaloneConfiguration.java
  common/cache/src/test/java/org/thingsboard/mqtt/broker/cache/TbRedisCacheConfigurationTest.java
  common/dao-api/src/main/java/org/thingsboard/mqtt/broker/dao/messages/DeviceMsgService.java
  common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/DevicePublishMsg.java
  common/util/pom.xml
  common/util/src/main/java/org/thingsboard/mqtt/broker/common/util/DevicePublishMsgUtil.java
  dao/src/main/java/org/thingsboard/mqtt/broker/dao/messages/ClientIdLastPacketIdCacheKey.java
  dao/src/main/java/org/thingsboard/mqtt/broker/dao/messages/ClientIdMessagesCacheKey.java
  dao/src/main/java/org/thingsboard/mqtt/broker/dao/messages/DeviceMsgServiceImpl.java
  dao/src/main/java/org/thingsboard/mqtt/broker/dao/messages/DevicePublishMsgEntity.java
  dao/src/test/java/org/thingsboard/mqtt/broker/dao/service/DeviceMsgServiceTest.java
  dao/src/test/resources/application-test.properties
  msa/tbmq/docker/Dockerfile
  pom.xml
Labels: Enhancement, Ignore for release
