Repository thingsboard/tbmq, pull requests merged in 2025-04, with the labels that each got.

#211 GCP GKE scripts 2.0.1
  k8s/gcp/README.md
  k8s/gcp/database-setup.yml
  k8s/gcp/k8s-delete-all.sh
  k8s/gcp/k8s-delete-tbmq.sh
  k8s/gcp/k8s-deploy-tbmq.sh
  k8s/gcp/k8s-install-tbmq.sh
  k8s/gcp/k8s-upgrade-tbmq.sh
  k8s/gcp/kafka/default-values-kafka.yml
  k8s/gcp/kafka/values-kafka.yml
  k8s/gcp/receipts/http-load-balancer.yml
  k8s/gcp/receipts/https-load-balancer.yml
  k8s/gcp/receipts/mqtt-load-balancer.yml
  k8s/gcp/redis/default-values-redis.yml
  k8s/gcp/redis/values-redis.yml
  k8s/gcp/tb-broker-cache-configmap.yml
  k8s/gcp/tb-broker-configmap.yml
  k8s/gcp/tb-broker-db-configmap.yml
  k8s/gcp/tb-broker-namespace.yml
  k8s/gcp/tb-broker.yml
Labels: Documentation, Enhancement

#212 Backpressure on data receiving
  application/src/main/java/org/thingsboard/mqtt/broker/server/AbstractMqttServerBootstrap.java
  application/src/main/resources/thingsboard-mqtt-broker.yml
Labels: Core

#213 GCP GKE scripts update for 2.1.0
  k8s/gcp/k8s-delete-tbmq.sh
  k8s/gcp/k8s-deploy-tbmq.sh
  k8s/gcp/redis/values-redis.yml
  k8s/gcp/tbmq-ie-configmap.yml
  k8s/gcp/tbmq-ie.yml
Labels: Documentation, Enhancement

#215 Added cluster.yml and gp3-def-sc.yml for Helm-based TBMQ installation on EKS
  k8s/helm/aws/cluster.yml
  k8s/helm/aws/gp3-def-sc.yml
Labels: Documentation, Enhancement

#217 Enable proxy protocol
  application/src/main/java/org/thingsboard/mqtt/broker/server/AbstractMqttChannelInitializer.java
  application/src/main/java/org/thingsboard/mqtt/broker/server/ip/ProxyIpFilter.java
  application/src/main/resources/thingsboard-mqtt-broker.yml
Labels: Core

#218 Bump Kafka, Redis and PostgreSQL versions
  application/src/test/java/org/thingsboard/mqtt/broker/AbstractPubSubIntegrationTest.java
  dao/src/test/java/org/thingsboard/mqtt/broker/dao/AbstractRedisClusterContainer.java
  dao/src/test/java/org/thingsboard/mqtt/broker/dao/AbstractRedisContainer.java
  dao/src/test/resources/sql-test.properties
  docker/backup-restore/README.md
  docker/cache/docker-compose.redis-cluster.yml
  docker/cache/docker-compose.redis-sentinel.yml
  docker/cache/docker-compose.redis.yml
  docker/docker-compose.yml
  k8s/aws/kafka/default-values-kafka.yml
  k8s/aws/kafka/values-kafka.yml
  k8s/azure/kafka/default-values-kafka.yml
  k8s/azure/kafka/values-kafka.yml
  k8s/gcp/kafka/default-values-kafka.yml
  k8s/gcp/kafka/values-kafka.yml
  k8s/minikube/backup-restore/README.md
  k8s/minikube/backup-restore/backup.yml
  k8s/minikube/backup-restore/restore.yml
  k8s/minikube/kafka/default-values-kafka.yml
  k8s/minikube/kafka/values-kafka.yml
  k8s/minikube/postgres.yml
  k8s/minikube/redis.yml
  msa/tbmq/configs/README.md
  msa/tbmq/configs/docker-compose.yml
Labels: Enhancement

#221 Feature/buffered delivery
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/DefaultPublishMsgDeliveryService.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/PublishMsgDeliveryService.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/delivery/BufferedMsgDeliveryService.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/delivery/BufferedMsgDeliveryServiceImpl.java
  application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/delivery/BufferedMsgDeliverySettings.java
  application/src/main/resources/thingsboard-mqtt-broker.yml
  application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/delivery/BufferedMsgDeliveryServiceImplTest.java
Labels: Core
